version: "3.7"
services:
  node_backend:
    container_name: "node_backend"
    build: .
    environment:
      WAIT_HOSTS: db:5432
    ports:
      - "8080:8080"
    depends_on:
      - db
   
  db:
    image: "postgres:12"
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  